# Letta Server Configuration
BRIDGE_LETTA_BASE_URL=http://localhost:8283
BRIDGE_LETTA_API_KEY=

# Bridge Configuration
BRIDGE_LOG_LEVEL=INFO
BRIDGE_MAX_AGENTS=10
BRIDGE_AGENT_TIMEOUT=300

# Tool Permissions
BRIDGE_ENABLE_WEB_SEARCH=true
BRIDGE_ENABLE_CODE_EXECUTION=true
BRIDGE_ENABLE_FILE_OPERATIONS=false